apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-module-4667
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-module-4667
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
